### ISSUE TITLE
The Agent doesn't have access to endpointslice, need to update the helm chart

### ISSUE THREAD

**Issue by Airren** [clusternet/charts#32]
![image-20221014154451678](https://user-images.githubusercontent.com/14846116/196145815-88636ebb-1ba0-4c20-88c0-cc9e8ff9b395.png)
![image](https://user-images.githubusercontent.com/14846116/196147055-912948ed-9dd2-4ca0-80e3-3354ef1eca1c.png)

**Comment by Airren** [comment]
I see that already been updated in the code repo, but not synced with the helm repo  https://clusternet.github.io/charts

**Comment by dixudx** [comment]
> I see that already been updated in the code repo, but not synced with the helm repo https://clusternet.github.io/charts

@Airren Need to release a new version to include those changes.

**Comment by dixudx** [comment]
@Airren Before a new release is coming out, you can try to [install charts from raw files](https://helm.sh/docs/helm/helm_install/).

**Comment by Airren** [comment]
Ok, no problem. Thanks!

**Comment by dixudx** [comment]
@Airren Please try new release `clusternet-agent` `0.9.1`.
